# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  init_env:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Authorization
        run: |
          cd env_init
          echo -e "正在授权 src 文件夹中的所有 sh 文件..."
          find "$(dirname "$0")" -type f -name "*.sh" -exec chmod +x {} \;
          echo -e "授权完成"
          cd src

      - name: Install
        run: |
          cd env_init/src
          ./init_all.sh

      - name: Clean
        run: | 
          cd env_init/src
          ./uninstall.sh

